
project_id = "jhokkuszubzngrcamfdb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://petjumper-supabase-lokhu.lovable.app"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
check_for_leaked_passwords = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false

[experimental]
plugins_scan = false
pubsub = false
graphql = false

[functions.filter_pet_policies]
verify_jwt = true
