
project_id = "jhokkuszubzngrcamfdb"

[functions.analyze_countries_policies]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.sync_airline_data]
verify_jwt = false

[functions.fetch_airlines]
verify_jwt = false

[functions.manage_users]
verify_jwt = false

