
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhokkuszubzngrcamfdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impob2trdXN6dWJ6bmdyY2FtZmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MTU0MzQsImV4cCI6MjA1MzA5MTQzNH0.raNfn4e-a6EISXQpuyez3mUDzKpao3Zs4AYJiJZrZbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined, // Use localStorage for session persistence
    storageKey: 'pet-travel-auth-token',
    flowType: 'pkce', // Use PKCE flow for enhanced security
  }
});

// Function to clear authentication data completely
export const clearAuthData = () => {
  try {
    if (typeof window === 'undefined') return true;
    
    localStorage.removeItem('pet-travel-auth-token');
    // Clear any other auth-related data that might be in localStorage
    const keysToRemove = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && (key.includes('supabase') || key.includes('auth'))) {
        keysToRemove.push(key);
      }
    }
    keysToRemove.forEach(key => localStorage.removeItem(key));
    
    console.log('Auth data cleared successfully');
    return true;
  } catch (error) {
    console.error('Error clearing auth data:', error);
    return false;
  }
};
